### ISSUE TITLE
Question - why port?

### ISSUE THREAD

**Issue by klesta490** [terrafx/terrafx.interop.mimalloc#19]
Why have you decided to port C code to C# instead of doing just wrapper library? What are the benefits? From my point of view it will be hard to stay up to date with  original C library.

Thanks for info Vladimir

**Comment by tannergooding** [comment]
It ensures that the code can participate in all the .NET specific optimizations such as library trimming, implicit instruction lightup on newer hardware, tiered compilation, and more. Likewise, it minimizes the number of native/managed transitions and therefore helps ensure the GC can perform better itself.

There isn't so much churn in the native mimalloc library to be problematic and tools like `ClangSharp` can assist in doing the bulk of the initial translation (with some manual validation and cleanup still required after for areas that ClangSharp can't handle).
